name: "Setup Clojure tooling"
description: "Install Java, Clojure CLI and Babashka"
inputs:
  cli:
    description: "Clojure CLI version to install"
  lein:
    description: "Leiningen build tool version to install"
  boot:
    description: "Boot build tool version to install"
  clj-kondo:
    description: "Clj-kondo linting tool version to install"
  cljstyle:
    description: "cljstyle formatting tool version to install"
  zprint:
    description: "zprint formatting tool version to install"
  github-token:
    description: >+
      To avoid rate limit errors, provide `secrets.GITHUB_TOKEN` value to this field.
      More info: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.3
      if: ${{ inputs.cli || inputs.lein || inputs.boot || inputs.clj-kondo || inputs.cljstyle || inputs.zprint }}
      with:
        cli: ${{ inputs.cli }}
        lein: ${{ inputs.lein }}
        boot: ${{ inputs.boot }}
        clj-kondo: ${{ inputs.clj-kondo }}
        cljstyle: ${{ inputs.cljstyle }}
        zprint: ${{ inputs.zprint }}
        github-token: ${{ inputs.github-token }}
